name: tin_book
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # GetX
  get: ^4.6.6

  dio: ^5.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter_easyloading: ^3.0.0
  dynamic_color: ^1.7.0
  file_picker: ^8.0.3
  url_launcher: ^6.2.6


  # 屏幕适配  https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.9.3

  # 下拉刷新  # 刷新  https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md
  pull_to_refresh: ^2.0.0



  cached_network_image: ^3.2.3
  logger: ^2.0.2
  shared_preferences: ^2.2.3



  crypto: ^3.0.3
  encrypt: ^5.0.1
  path_provider: ^2.1.4

  permission_handler: ^11.2.0

#  数据库，移动端用sqflite  桌面端用sqflite_common_ffi
  sqflite: ^2.3.1
  sqflite_common_ffi: ^2.3.3

  archive: ^3.4.10
#  epub_parser: ^3.0.1


#  //ant_reader
  shelf: ^1.4.1
  flutter_inappwebview: ^6.0.0
  path: ^1.9.0
#  wakelock_plus 是一个 Dart 包，主要用于 Flutter 应用中防止屏幕锁定或休眠，这对于后台任务处理非常有用，比如播放音乐、下载文件或者执行长时间运行的任务。
  wakelock_plus: ^1.2.5
  epubx: ^4.0.0
  image: ^3.3.0
  icons_plus: ^5.0.0
  contentsize_tabbarview:
    git:
      url: https://github.com/Anxcye/contentsize_tabbarview.git
      ref: feat/animation
  logging: ^1.2.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  flutter_tts: ^4.0.2
  battery_plus: ^6.1.0
#  PhotoView使图像能够通过用户手势（如捏合、旋转和拖动）进行缩放和平移。
  photo_view: ^0.15.0

  flutter_smart_dialog: ^4.9.8+3

  saver_gallery: ^3.0.6
  share_plus: ^10.0.2
  device_info_plus: ^10.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  flutter_colorpicker: ^1.0.3
#  允许您在可滚动内容上放置标题，当内容滚动时，标题将粘在容器的顶部。
  sticky_headers: ^0.3.0+2
  chinese_font_library: ^1.2.0
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_html: ^3.0.0-beta.2


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    #    - assets/ic_launcher.png
    - assets/
    - assets/desktop/
    - assets/fonts/SourceHanSerifSC-Regular.otf
    - assets/foliate-js/
    - assets/foliate-js/vendor/
    - assets/foliate-js/vendor/pdfjs/
flutter_intl:
  enabled: true
