name: tin_book
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # GetX
  get: ^4.6.6

  dio: ^5.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter_easyloading: ^3.0.0


  # 屏幕适配  https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.9.0

  # 下拉刷新  # 刷新  https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md
  pull_to_refresh: ^2.0.0



  cached_network_image: ^3.2.3
  logger: ^2.0.2
  shared_preferences: ^2.2.2



  crypto: ^3.0.3
  encrypt: ^5.0.1
  path_provider: ^2.0.15

  permission_handler: ^11.2.0

#  数据库，移动端用sqflite  桌面端用sqflite_common_ffi
  sqflite: ^2.3.1
  sqflite_common_ffi: ^2.3.3

  archive: ^3.4.10
  epub_parser: ^3.0.1
#  flutter_widget_from_html: ^0.14.11


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    #    - assets/ic_launcher.png
    - assets/
    - assets/desktop/

